apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      server: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: server
        image: ubuntu:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500Mi"
        command: ["/bin/bash", "-c"]
        args:
        - sleep 300
