apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv01
  accessModes:
  - ReadWriteOnce
  storageClassName: admstor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: admstor
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storagedemo
  labels:
    name: pvcdemo
spec:
  containers:
  - name: demo-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvstor
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pvstor
    persistentVolumeClaim:
      claimName: mypvc
