apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: challenge
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/challenge-pv
