apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
spec:
  capacity:
    storage: 2Gi
  storageClassName: challenge
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/challenge-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc
spec:
  storageClassName: challenge
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-challenge
  labels:
    name: pvc-challenge
spec:
  containers:
  - name: challenge-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvstorchallenge
      mountPath: /var/www/html
  volumes:
  - name: pvstorchallenge
    persistentVolumeClaim:
      claimName: challenge-pvc
